codecov:
  token: 74221eff-6521-4da4-8a20-81b2814c213c
comment:
  behaviour: default
  require_changes: false
  require_head: false     # default yes
  require_base: false     # default yes
ignore:
  - "src/tests/*”
